# Generated by Django 4.2 on 2023-04-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_article_alter_facility_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='button',
            field=models.CharField(default='button', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='button1', upload_to='article_images'),
            preserve_default=False,
        ),
    ]
