# Generated by Django 4.2 on 2023-05-01 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='blogpost_images')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('user', models.CharField(max_length=100)),
                ('viewers', models.CharField(max_length=50)),
                ('commentary', models.CharField(max_length=1000)),
                ('Button', models.CharField(default='View More', max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.categories')),
            ],
            options={
                'verbose_name_plural': 'BlogPost',
            },
        ),
    ]
