# Generated by Django 4.2 on 2023-05-01 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(choices=[('Inquiry', 'Inquiry'), ('Complaint', 'Complaint')], max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
