# Generated by Django 4.2 on 2023-05-01 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='description',
            new_name='message',
        ),
    ]
